import pandas as pd

testset = """
Livet i et globaliseret samfund, hvor sprog og identitet med fuld fart udvikles, kan være svært at finde rundt i, og det skaber flere sproglige udfordringer, som kan være svære at tilpasse sig. I denne tid diskuteres også antallet af køn og deres forskellige kønsbetegnelser, som kan være helt forvirrende at få overblik over. Dette giver ikke bare sproglige, men også samfundsmæssige udfordringer, og som kønsforskeren Rikke Andreassen udtaler, så kan det ”være en udfordring, fordi hele vores verden er indrettet efter et system med to køn” (s. 1, l. 22-23). For en del år siden offentliggjorde Facebook også deres 71 køn, og jeg husker da selv, hvordan jeg dengang tænkte, at jeg var dreng, hun var pige, og det burde da være meget simpelt, og at det måske var en lidt for stor overdrivelse at udnævne hele 69 nye køn. Men var det for naivt at tænke sådan? Har Facebook i virkeligheden gjort det rigtige og vist den rigtige vej frem? Og skal vi andre bare følge blindt med? Sam Smith stod for nogle måneder siden også frem på de sociale medier, hvor det fremgik, at Smith nu definerer sig selv som ikke-binær, og ikke længere vil kaldes ’ham’ men derimod ’de’ eller ’dem’. Hvorvidt skal vi efterleve dette? Det er vel ikke nyt, at nogle mennesker ikke føler sig som enten dreng eller pige, men i denne tid siger mange flere det højt, og det skaber opmærksomhed. Selvom gruppen af sådanne mennesker stadig er forholdsvis lille, så har den de sidste år steget voldsomt, og af netop denne grund skal samfundet vel tage hensyn til dem. Selvom det kunne være rart med et samfund kun opbygget af drenge og piger, hvor, som Andreassen udtaler, ”manden og kvinden er skabt for hinanden” (s. 1, l. 25), så må vi vel snart indse, at realiteten er kompliceret. Skal vi nu ændre sproget for at tilpasse os denne nye minoritet? Hvor meget magt skal sådanne gruppe have, og hvordan sikrer man, at de ikke ødelægger vores fælles sprog? Og bliver det ikke for svært for den enkelte at navigere mellem, hvad forskellige individer vil kaldes?
Denne voksende konflikt, som hurtigt kan blive forvirrende at finde rundt i, har fået Kasper Madsbøll Christensen til at give læseren et overblik i en artikel offentliggjort på DR.dk d. 16 september 2019. I artiklen interviewes kønsforskeren Rikke Andreassen, og hun mener, at ”det er en god måde at vise respekt for folk, når man lytter til, hvad de gerne selv vil kaldes” (s. 2, l. 35), og det giver da rigtig god mening. I private samtaler, og hvis man kender personen, skal man vel så vidt muligt respektere og omtale personen, som personen ønsker. Det kan dog blive en del sværere i offentlige debatter eller samtaler, hvor der ikke på samme måde kan tages hensyn. At omtale personer som ’de’ eller ’dem’ kan forvirre samtale, og, som Rikke Andreassen siger, så har de ”I Sverige (…) betegnelsen ’hen’, der dog ikke er slået igennem i Danmark” (s. 2, l. 35-36), og måske er det også noget, som snart skal indføres i det danske sprog. Dette kunne i hvert fald være med til at løse problemet i de offentlige debatter, og vise disse grupper, at vi respektere dem, som de er. Men måske er dette at gå for langt? Er vores sprog ikke for helligt og centralt til bare lige at ændre, fordi nogle mennesker pludselig føler, at de ikke tilhører de traditionelle køn? Ifølge Mette Østergaard, som præsenterede sit svar på Sam Smiths udmelding i en leder fra Berlinske d. 7 oktober 2019, er sproget for vigtigt for fællesskabet til at ændre på baggrund af nogle lille interessegrupper. Hun mener, at samfundet ikke bør ”give et mindretal vetoret over, hvordan vores sprog skal bruges eller fortolkes. Dertil er sproget for central en del af vores kultur og sammenhængskraft” (s. 2, l. 36-37), og det kan jeg godt forstå. For hvad bliver det næste? Bliver det 69 nye forskellige pronomener, som alle repræsenterer deres eget køn? Det bliver yderst umuligt at finde rundt i, hvad man skal kalde folk uden, at de bliver fornærmet over, at man ikke omtaler dem korrekt. Men er det ikke også, at det gå lidt for langt? Personligt mener jeg ikke, at man skal være bange for, at sproget udvikler sig i sådan en retning. Mette kan have ret, at vi ikke skal lade mindre grupper styrer, hvordan vores sprog udvikler sig, men netop denne gruppe vokser voldsomt lige nu, og individer i de 69 andre køn er vel ikke længere en lille gruppe, og i vores nuværende samfund, hvor der er meget fokus på ligestilling, og at alle skal respekteres og ikke krænkes, som man blandt andet ser ved Copenhagen Pride, skal man vel respektere alle slags mennesker. De er efterhånden blevet mellemstore, og sådanne grupper skal man vel også tage hensyn til. 
Mette Østergaards udtalelser faldt ikke i god jord hos alle, og det fik Ole Rosenstand Svidt til at give hans holdning på problemet i en kommentar i GAFFA d. 23 oktober 2019. Svidt mener, at man af højlighed skal respektere individers holdninger, og af den grund skal kalde dem det, som de ønsker. Ifølge Ole Rosenstand Svidt, så ville det ”være lettere med et kønsneutralt a la det svenske ”hen” som supplement til han og hun” (s. 2, l. 41-42), og det blev også tidligere i denne artikel fremhævet, at Rikke Andreassen havde samme holdning. Men er dette den rette løsning? At ændre på det danske sprog skal ske med omhu, og især pronomener er noget, som man sjældent ændrer. Det er noget af det mest centrale af vores sprog, og så skal man virkelig passe på. Mette Østergaard er i hvert fald uenig i Svidts og Andreassens synspunkt: ”I den danske ordbog findes det svenske ord for intetkøn »hen« ikke. Derfor skal vi ikke bruge det.” (s. 1, l. 12). Det er vel ordbogen, som hele sproget bygger på, og den der styrer, hvordan sproget skal bruges. Kan man så bare opfinde nye ord? Skal man bare se bort fra, at små grupper pludselig ændrer sproget? Ja, det skal man. Der kommer hele tiden nye ord til i ordbogen, og det sker netop af den grund, at befolkningen bruger ordene. Med min daglige gang i gymnasiet hører og bruger jeg dagligt ord såsom: ”noob” og ”cringe”, som begge ikke er med i ordbogen. Det er del af de unges sprog, og med sprogets udvikling bliver det måske også en del af den danske ordbog. Ifølge Ole Rosenstand Svidt, så udvikler sproget sig ”såvel som virkeligheden (…), og så må vi følge med efter bedste evne.” (s. 2, l. 44). Sproget er ikke, som det har været, og i fremtiden opstår sikkert også flere ord, som vil blive en del af det danske sprog. Sproget er én af grundstenene for vores nation, befolkning og danskheden, og i takt med at netop vi alle udvikler os, så bliver sproget også nødt til at følge med. 
Mette Østergaards artikel er præget af manglende selvindsigt og stor kritik af, hvordan andre medier forholder sig til Sam Smiths udtalelser. Hun kan vel have ret i, at en så ”trods alt - lille interessegruppe” (s. 1, l. 11) ikke skal kunne ændre på sproget, og at vi skal passe på med, at ændre sproget efter alle små minoritetsgrupper, men netop her, må hun prøve at sætte sig ind i deres situation, selvom jeg da også selv kan mærke, at det kan være svært. Mette Østergaard har ret i, at samfundet, som Andreassen, der med sin høje etos har nemmere ved at overbevise sin læser om sit synspunkt, også beskriver, er opbygget efter de to traditionelle køn, og herunder vel også sproget. Hvis Mette Østergaard gerne vil overbevise sin læser om, at netop hendes synsvinkel er den rigtige, så skal hun nok nærmere prøve enten at skabe rygdækning ved eksperter, som deler hendes synsvinkel, eller sætte sig ind i Sam Smiths perspektiv. I sidste ende prøver Østergaard bare at værne om sin nation, men hun må forstå, at alt konstant er under udvikling, og at sproget, køn, identitet og især samfundet i fremtiden vil være anderledes end, hvad vi kender det som i dag.
Debatten om, hvorvidt der skal tilføjes flere køn, eller om sproget skal ændres, vil nok diskuteret langt ud i fremtiden. Den vil udfordre vores forståelse af de forskellige køn, identitet og ikke mindst sproget. Her er det vigtigt, at vi som mennesker handler på bedste vis og stille og forsigtigt udvikler vores samfund, så vi sikrer, at så mange som muligt respekteres og så få krænkes. Facebooks 71 køn er nok kun de første, og måske vil vi om få årtier være langt over dette, så det gælder om at finde en løsning, hvor alle kan være med. Du må sætte dig ind i vores medmenneskers synspunkter, og du må forstå, at andre føler anderledes end dig. Du må have forståelse for, at samfundet hele tiden udvikler sig, selvom det føles ubehageligt. Vi kan alle lære af at blive udfordret, og så må vi hjælpe hinanden, så alle kan følge med. 
"""

testset = testset.lower().strip(",").strip(".").strip(":").strip("\n")

def build_dataset(sentence):
    block_size = 8 # amount of previous characters to determine next
    X = []
    words = sentence.lower().split(" ")
    context = ["."] * block_size
    for i in range(len(words) + block_size):
        X.append(context)
        next_word = "." if i > len(words)-1 else words[i]
        context = context[1:] + [next_word] # crop context and append next character
    return X

test_dataset = build_dataset(testset)
print(len(test_dataset))
df = pd.DataFrame(test_dataset)

full_stop = df.iloc[(df[3].str[-1].values == ".") & (df[3].values != ".")]
full_stop["label"] = 1
full_stop[3] = full_stop[3].map(lambda x: x[:-1])
comma = df.iloc[(df[3].str[-1].values == ",")]
comma["label"] = 2
comma[3] = comma[3].map(lambda x: x[:-1])
colon = df.iloc[(df[3].str[-1].values == ":")]
colon["label"] = 3
colon[3] = colon[3].map(lambda x: x[:-1])
rest = df.iloc[(df[3].str[-1].values != ".") & (df[3].str[-1].values != ",") & (df[3].str[-1].values != ":")]
rest["label"] = 0

data_frames = [full_stop, comma, colon, rest]
df_merged = pd.concat(data_frames)
df_merged.reset_index()
print(df_merged.head(100))
print(len(df_merged))

df_merged.to_csv("Datasets/testset.csv", encoding="UTF-8", index=False)